use_frameworks!

platform :ios, '8.0'

target 'YQTestNetworking_Example' do
  pod 'YQTestNetworking', :path => '../'

  target 'YQTestNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
